backend:
  name: git-gateway
  branch: master
    # local_backend: true
media_folder: "public/static/images"
public_folder: "/static/images"
  # media_library:
  #   name: cloudinary
  #   config:
  #     cloud_name: abhiruchi
  #     api_key: 622373855911142
collections:
  - name: "Recipe"
    label: "Recipe"
    folder: "data/recipe"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Layout", name: "layout", widget: "hidden", default: "PostFrontMatter"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - label: "Recipe"
        name: subrecipe
        widget: list
        fields:
          - label: Name
            name: name
            widget: string
            required: false
          - label: Ingredients
            name: ingredients
            widget: text
          - label: Instructions
            name: instructions
            widget: text
          - label: Story
            name: story
            widget: list
            summary: "{{fields.title}} - {{fields.description}}"
            fields:
              - label: Title
                name: title
                widget: string
                required: false
              - label: Description
                name: description
                widget: string
                required: true
              - label: Picture
                name: image
                widget: image
  - name: "Projects"
    label: "Projects"
    folder: "data/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget:"string"}
