backend:
  name: git-gateway
  branch: master
media_folder: "public/static/images"
public_folder: "/static/images"
  # media_library:
  #   name: cloudinary
  #   config:
  #     cloud_name: abhiruchi
  #     api_key: 622373855911142
collections:
  - name: "Recipe"
    label: "Recipe"
    folder: "data/recipe"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "PostSimple"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Featured Image", name: "images", widget: "list", field: {label: "Image", name: "image", widget: "image"}}
      - {label: "Body", name: "body", widget: "markdown"}
